// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeType = "RootNode" | "RoundedSegment" | "Segment" | "Circle" | "Triangle" | "FilledCircle" | "Ellipse" | "Trapezoid" | "Polygon";
